// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDFManager.Core;

namespace PDFManager.Core.Migrations
{
    [DbContext(typeof(PDFManagerContext))]
    [Migration("20210913005959_DocumentIdentificationAdded")]
    partial class DocumentIdentificationAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("PDFManager.Core.PDFDocument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Archived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentAuthor")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DocumentBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("DocumentDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DocumentVisibility")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdentificationString")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PDFDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
